
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comfy-switch-samplers"
version = "0.1.1"
description = "Switch sampler nodes for ComfyUI"
authors = [
  { name="Azazeal Creations" }
]
license = "MIT"
